services:
  mongo:
    container_name: realine-mongo-db
    image: 'bitnami/mongodb:latest'
    ports:
      - 27170:27017
    volumes:
      - './cache/:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=fD4Eo6I8no5Dlo0v8QhWTo1aKC
      - MONGODB_ROOT_USER=realine

  # Sections below commented cause not working with hmr

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: app.Dockerfile
  #     args:
  #       - app=frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/app/
  #     - /app/node_modules/
  #   command: sh -c "yarn run dev --filter=frontend"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: app.Dockerfile
  #     args:
  #       - app=backend
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./:/app/
  #     - /app/node_modules/
  #   command: sh -c "yarn run dev --filter=backend"